// Copy for the editorial portfolio layout. Professional facts come from i18n.js.
const portfolioCopy = {
  en: {
    experience: 'Experience',
    experience_heading: 'Professional experience',
    projects_heading: 'Projects & practice',
    about_heading: 'About me',
    hero_greeting: "Hey, I'm",
    hero_intro: 'I’m a <strong>Pentester</strong> passionate about <strong>ethical hacking and offensive security</strong>. I like understanding how things work... and then breaking them in a controlled environments :)',
    hero_contact: 'Get in touch',
    hero_focus: 'OFFENSIVE SECURITY',
    social_label: 'Social profiles and contact',
    skip_content: 'Skip to content',
    theme_light: 'Switch to light theme',
    theme_dark: 'Switch to dark theme',
    orange_role: 'Pentester · Work-study',
    doomap_role: 'IT, security & development · Work-study',
    telecom_role: 'Security operations · Internship',
    notes_summary: 'A public knowledge base on offensive cybersecurity covering reconnaissance, web security, Linux, Active Directory, CTF write-ups, CMS exploitation, tools, Wi-Fi and useful resources. It brings together practical notes, methodologies and examples from my learning and research.',
    notes_visits: 'visits',
    htb_title: 'Hack The Box',
    htb_summary: 'More than 100 machines solved across Linux, Windows and Active Directory environments, from easy to hard, plus over 25 HTB Academy modules completed. My approach covers reconnaissance, exploitation, privilege escalation, pivoting and post-exploitation.',
    practice_preview_heading: 'Hands-on offensive security',
    practice_linux: 'Linux machines',
    practice_modules: 'Academy modules',
    practice_web_labs: 'Web labs',
    portswigger_summary: '269 web labs completed across the Apprentice, Practitioner and Expert levels, covering 31 vulnerability categories, including XSS, SQLi, SSRF, CSRF, IDOR, API security, HTTP request smuggling, JWT and web cache attacks.',
    ai_title: 'AI for VoIP telephony',
    ai_summary: 'An AI solution for Asterisk developed at Doomap, combining speech recognition, language models and speech synthesis to assist with alarm handling and reduce calls caused by user errors.',
    visit_notes: 'Explore the notes',
    visit_profile: 'View my profile',
    project_details: 'Technical details',
    cert_heading: 'Certifications',
    verify_cert: 'View certification',
    cert_preparing: 'In preparation',
    education_heading: 'Education',
    view_program: 'View programme',
    platform_label: 'Platform',
    languages_heading: 'Languages',
    language_spanish: 'Spanish',
    language_catalan: 'Catalan',
    language_french: 'French',
    language_english: 'English',
    language_native: 'Native language',
    language_fluent: 'Fluent',
    language_technical: 'Technical',
    about_first: 'I’m Jordan Macia De Las Heras, a Pentester with a background in networking, systems administration and development. This perspective helps me assess web applications and infrastructure from an authorised attacker’s point of view.',
    about_second: 'Through professional roles in pentesting, infrastructure migration and security operations, I have worked on security testing, hardening and incident-response workflows.',
    about_third: 'I continue to develop my skills through web labs, CTFs and Linux, Windows and Active Directory environments, with a focus on clear, reproducible findings and useful reporting.',
    footer_note: 'Pentester. Always learning.',
    footer_rights: 'All rights reserved.',
    notes_preview_label: 'An open notebook for offensive security',
    notes_preview_sections: 'Web security / Privilege escalation / Methodology',
    ai_preview_label: 'From an incoming call to an AI-assisted response',
    ai_input: 'Incoming call',
    ai_output: 'Voice response',
  },
  es: {
    experience: 'Experiencia',
    experience_heading: 'Experiencia profesional',
    projects_heading: 'Proyectos y práctica',
    about_heading: 'Sobre mí',
    hero_greeting: 'Hey, soy',
    hero_intro: 'Soy un <strong>Pentester</strong> apasionado del <strong>hacking ético y la seguridad ofensiva</strong>. Me gusta entender cómo funcionan las cosas... y después destruirlas, de forma controlada :)',
    hero_contact: 'Contáctame',
    hero_focus: 'SEGURIDAD OFENSIVA',
    social_label: 'Redes sociales y contacto',
    skip_content: 'Ir al contenido',
    theme_light: 'Cambiar al tema claro',
    theme_dark: 'Cambiar al tema oscuro',
    orange_role: 'Pentester · Formación en alternancia',
    doomap_role: 'IT, seguridad y desarrollo · Formación en alternancia',
    telecom_role: 'Operaciones de seguridad · Prácticas',
    notes_summary: 'Una base de conocimientos pública sobre ciberseguridad ofensiva: reconocimiento, seguridad web, Linux, Active Directory, write-ups de CTF, explotación de CMS, herramientas, Wi-Fi y recursos útiles. Reúne notas prácticas, metodologías y ejemplos de mi aprendizaje e investigación.',
    notes_visits: 'visitas',
    htb_title: 'Hack The Box',
    htb_summary: 'Más de 100 máquinas resueltas en entornos Linux, Windows y Active Directory, de nivel fácil a difícil, y más de 25 módulos de HTB Academy completados. Mi enfoque abarca reconocimiento, explotación, escalada de privilegios, pivoting y postexplotación.',
    practice_preview_heading: 'Seguridad ofensiva en práctica',
    practice_linux: 'Máquinas Linux',
    practice_modules: 'Módulos Academy',
    practice_web_labs: 'Labs web',
    portswigger_summary: '269 laboratorios web completados en los niveles Apprentice, Practitioner y Expert, que cubren 31 categorías de vulnerabilidades, entre ellas XSS, SQLi, SSRF, CSRF, IDOR, seguridad de API, HTTP request smuggling, JWT y ataques a la caché web.',
    ai_title: 'IA para telefonía VoIP',
    ai_summary: 'Una solución de IA para Asterisk desarrollada en Doomap que combina reconocimiento de voz, modelos de lenguaje y síntesis de voz para asistir en la gestión de alarmas y reducir las llamadas causadas por errores de uso.',
    visit_notes: 'Explorar las notas',
    visit_profile: 'Ver mi perfil',
    project_details: 'Detalles técnicos',
    cert_heading: 'Certificaciones',
    verify_cert: 'Ver certificación',
    cert_preparing: 'En preparación',
    education_heading: 'Formación',
    footer_rights: 'Todos los derechos reservados.',
    view_program: 'Ver formación',
    platform_label: 'Plataforma',
    languages_heading: 'Idiomas',
    language_spanish: 'Español',
    language_catalan: 'Catalán',
    language_french: 'Francés',
    language_english: 'Inglés',
    language_native: 'Lengua materna',
    language_fluent: 'Fluido',
    language_technical: 'Técnico',
    about_first: 'Soy Jordan Macia De Las Heras, Pentester con una base en redes, administración de sistemas y desarrollo. Esta visión me permite evaluar aplicaciones web e infraestructuras desde la perspectiva de un atacante autorizado.',
    about_second: 'En mis experiencias profesionales en pentesting, migración de infraestructuras y operaciones de seguridad he trabajado en pruebas de seguridad, endurecimiento y gestión de incidentes.',
    about_third: 'Sigo desarrollando mis habilidades con laboratorios web, CTF y entornos Linux, Windows y Active Directory, poniendo el foco en hallazgos claros, reproducibles e informes útiles.',
    footer_note: 'Pentester. Siempre aprendiendo.',
    notes_preview_label: 'Un cuaderno abierto de seguridad ofensiva',
    notes_preview_sections: 'Seguridad web / Escalada de privilegios / Metodología',
    ai_preview_label: 'De una llamada entrante a una respuesta asistida por IA',
    ai_input: 'Llamada entrante',
    ai_output: 'Respuesta de voz',
  },
  fr: {
    experience: 'Expérience',
    experience_heading: 'Expérience professionnelle',
    projects_heading: 'Projets & pratique',
    about_heading: 'À propos',
    hero_greeting: 'Salut, moi c’est',
    hero_intro: '<strong>Pentester</strong> passionné par le <strong>hacking éthique et la sécurité offensive</strong>, j’aime comprendre comment les choses fonctionnent... puis les casser, dans un cadre contrôlé :)',
    hero_contact: 'Me contacter',
    hero_focus: 'SÉCURITÉ OFFENSIVE',
    social_label: 'Réseaux sociaux et contact',
    skip_content: 'Aller au contenu',
    theme_light: 'Passer au thème clair',
    theme_dark: 'Passer au thème sombre',
    orange_role: 'Pentester · Alternance',
    doomap_role: 'IT, sécurité & développement · Alternance',
    telecom_role: 'Opérations de sécurité · Stage',
    notes_summary: 'Une base de connaissances publique en cybersécurité offensive : reconnaissance, sécurité web, Linux, Active Directory, write-ups de CTF, exploitation de CMS, outils, Wi-Fi et ressources utiles. Elle rassemble des notes pratiques, méthodes et exemples issus de mon apprentissage et de mes recherches.',
    notes_visits: 'visites',
    htb_title: 'Hack The Box',
    htb_summary: 'Résolution de plus de 100 machines dans des environnements Linux, Windows et Active Directory, de niveau facile à difficile, et validation de plus de 25 modules HTB Academy. Mon approche couvre la reconnaissance, l’exploitation, l’élévation de privilèges, le pivoting et la post-exploitation.',
    practice_preview_heading: 'La sécurité offensive en pratique',
    practice_linux: 'Machines Linux',
    practice_modules: 'Modules Academy',
    practice_web_labs: 'Labs web',
    portswigger_summary: 'Réalisation de 269 laboratoires web aux niveaux Apprentice, Practitioner et Expert, couvrant 31 catégories de vulnérabilités, dont XSS, SQLi, SSRF, CSRF, IDOR, sécurité des API, HTTP request smuggling, JWT et attaques sur le cache web.',
    ai_title: 'IA pour la téléphonie VoIP',
    ai_summary: 'Une solution IA pour Asterisk développée chez Doomap, combinant reconnaissance vocale, modèles de langage et synthèse vocale pour assister la gestion des alarmes et réduire les appels liés à des erreurs d’utilisation.',
    visit_notes: 'Explorer les notes',
    visit_profile: 'Voir mon profil',
    project_details: 'Détails techniques',
    cert_heading: 'Certifications',
    verify_cert: 'Voir la certification',
    cert_preparing: 'En cours de préparation',
    education_heading: 'Formation',
    footer_rights: 'Tous droits réservés.',
    view_program: 'Voir la formation',
    platform_label: 'Plateforme',
    languages_heading: 'Langues',
    language_spanish: 'Espagnol',
    language_catalan: 'Catalan',
    language_french: 'Français',
    language_english: 'Anglais',
    language_native: 'Langue maternelle',
    language_fluent: 'Courant',
    language_technical: 'Technique',
    about_first: 'Je suis Jordan Macia De Las Heras, Pentester avec des bases en réseaux, administration système et développement. Cette vision me permet d’évaluer des applications web et des infrastructures du point de vue d’un attaquant autorisé.',
    about_second: 'Mes expériences en pentest, migration d’infrastructure et opérations de sécurité m’ont amené à travailler sur les tests de sécurité, le durcissement et la gestion des incidents.',
    about_third: 'Je développe également mes compétences grâce aux laboratoires web, aux CTF et aux environnements Linux, Windows et Active Directory, avec une attention particulière à des constats clairs, reproductibles et exploitables.',
    footer_note: 'Pentester. Toujours en apprentissage.',
    notes_preview_label: 'Un carnet ouvert de sécurité offensive',
    notes_preview_sections: 'Sécurité web / Élévation de privilèges / Méthodologie',
    ai_preview_label: 'D’un appel entrant à une réponse assistée par IA',
    ai_input: 'Appel entrant',
    ai_output: 'Réponse vocale',
  },
  ad: {
    experience: 'Experiència',
    experience_heading: 'Experiència professional',
    projects_heading: 'Projectes i pràctica',
    about_heading: 'Sobre mi',
    hero_greeting: 'Ei, soc',
    hero_intro: 'Soc un <strong>Pentester</strong> apassionat del <strong>hacking ètic i la seguretat ofensiva</strong>. M’agrada entendre com funcionen les coses... i després destruir-les, de manera controlada :)',
    hero_contact: 'Contacta’m',
    hero_focus: 'SEGURETAT OFENSIVA',
    social_label: 'Xarxes socials i contacte',
    skip_content: 'Anar al contingut',
    theme_light: 'Canviar al tema clar',
    theme_dark: 'Canviar al tema fosc',
    orange_role: 'Pentester · Formació dual',
    doomap_role: 'IT, seguretat i desenvolupament · Formació dual',
    telecom_role: 'Operacions de seguretat · Pràctiques',
    notes_summary: 'Una base de coneixements pública sobre ciberseguretat ofensiva: reconeixement, seguretat web, Linux, Active Directory, write-ups de CTF, explotació de CMS, eines, Wi-Fi i recursos útils. Aplega notes pràctiques, metodologies i exemples del meu aprenentatge i de la meva recerca.',
    notes_visits: 'visites',
    htb_title: 'Hack The Box',
    htb_summary: 'Més de 100 màquines resoltes en entorns Linux, Windows i Active Directory, de nivell fàcil a difícil, i més de 25 mòduls d’HTB Academy completats. El meu enfocament inclou reconeixement, explotació, escalada de privilegis, pivoting i postexplotació.',
    practice_preview_heading: 'Seguretat ofensiva en pràctica',
    practice_linux: 'Màquines Linux',
    practice_modules: 'Mòduls Academy',
    practice_web_labs: 'Labs web',
    portswigger_summary: '269 laboratoris web completats als nivells Apprentice, Practitioner i Expert, que cobreixen 31 categories de vulnerabilitats, entre les quals XSS, SQLi, SSRF, CSRF, IDOR, seguretat d’API, HTTP request smuggling, JWT i atacs a la memòria cau web.',
    ai_title: 'IA per a telefonia VoIP',
    ai_summary: 'Una solució d’IA per a Asterisk desenvolupada a Doomap que combina reconeixement de veu, models de llenguatge i síntesi de veu per donar suport a la gestió d’alarmes i reduir les trucades causades per errors d’ús.',
    visit_notes: 'Explorar les notes',
    visit_profile: 'Veure el meu perfil',
    project_details: 'Detalls tècnics',
    cert_heading: 'Certificacions',
    verify_cert: 'Veure certificació',
    cert_preparing: 'En preparació',
    education_heading: 'Formació',
    footer_rights: 'Tots els drets reservats.',
    view_program: 'Veure formació',
    platform_label: 'Plataforma',
    languages_heading: 'Idiomes',
    language_spanish: 'Espanyol',
    language_catalan: 'Català',
    language_french: 'Francès',
    language_english: 'Anglès',
    language_native: 'Llengua materna',
    language_fluent: 'Fluid',
    language_technical: 'Tècnic',
    about_first: 'Soc Jordan Macia De Las Heras, Pentester amb una base en xarxes, administració de sistemes i desenvolupament. Aquesta visió em permet avaluar aplicacions web i infraestructures des de la perspectiva d’un atacant autoritzat.',
    about_second: 'En les meves experiències en pentesting, migració d’infraestructures i operacions de seguretat he treballat en proves de seguretat, enduriment i gestió d’incidències.',
    about_third: 'Continuo desenvolupant les meves habilitats amb laboratoris web, CTF i entorns Linux, Windows i Active Directory, amb l’objectiu d’obtenir resultats clars, reproduïbles i informes útils.',
    footer_note: 'Pentester. Sempre aprenent.',
    notes_preview_label: 'Un quadern obert de seguretat ofensiva',
    notes_preview_sections: 'Seguretat web / Escalada de privilegis / Metodologia',
    ai_preview_label: 'D’una trucada entrant a una resposta assistida per IA',
    ai_input: 'Trucada entrant',
    ai_output: 'Resposta de veu',
  },
};

export default portfolioCopy;
